package com.poscaisse.domain;

public enum Permission {
    REGISTER_OPEN, SELL, DISCOUNT_APPLY, DISCOUNT_HIGH, PRICE_EDIT, LINE_DELETE, ORDER_CANCEL,
    TICKET_CANCEL, REFUND, DRAWER_OPEN, REVENUE_VIEW, CASH_MOVEMENT, REGISTER_CLOSE, DAILY_CLOSE,
    PRODUCTS_MANAGE, USERS_MANAGE, SETTINGS_MANAGE, REPORTS_VIEW, TICKETS_VIEW, TICKETS_REPRINT,
    BACKOFFICE_ACCESS, AUDIT_VIEW, CUSTOMER_CREDIT
}
